#!/bin/bash
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_60"
export PATH=$JAVA_HOME/bin:$PATH
cd $OPENSHIFT_REPO_DIR
nohup $JAVA_HOME/bin/java -jar build/libs/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &